/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenêtre;

import Metier.Association;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Valoo
 */
public class FAjoutAssociation extends FMaster
{
    /**
     * Creates new form FInsertionAssociation
     */
    public FAjoutAssociation()
    {
        initComponents();
    }
    public FAjoutAssociation(Association a)
    {
        initComponents();
        tfRefAssoc.setText(a.getRefAsso());
        tfVille.setText(a.getVille());
        tfAdresse.setText(a.getAdresse());
        tfNomResp.setText(a.getNomRepsonsable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTitre = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        lblRefAssoc = new javax.swing.JLabel();
        tfRefAssoc = new javax.swing.JTextField();
        lblVille = new javax.swing.JLabel();
        tfVille = new javax.swing.JTextField();
        lblAdresse = new javax.swing.JLabel();
        tfAdresse = new javax.swing.JTextField();
        lblNomResp = new javax.swing.JLabel();
        tfNomResp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter une Association");

        lblTitre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitre.setForeground(new java.awt.Color(0, 255, 0));
        lblTitre.setText("Ajouter une Association");

        btnOk.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOkActionPerformed(evt);
            }
        });

        btnAnnuler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnnulerActionPerformed(evt);
            }
        });

        lblRefAssoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRefAssoc.setText("Reference Asoociation");

        tfRefAssoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfRefAssoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblVille.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblVille.setText("Ville");

        tfVille.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfVille.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblAdresse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAdresse.setText("Adresse");

        tfAdresse.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfAdresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNomResp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNomResp.setText("Nom du reposnsable");

        tfNomResp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfNomResp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfNomResp, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addComponent(lblRefAssoc)
                    .addComponent(tfRefAssoc)
                    .addComponent(lblVille)
                    .addComponent(tfVille)
                    .addComponent(lblAdresse)
                    .addComponent(tfAdresse)
                    .addComponent(lblNomResp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitre))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre)
                .addGap(33, 33, 33)
                .addComponent(lblRefAssoc)
                .addGap(18, 18, 18)
                .addComponent(tfRefAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVille)
                .addGap(18, 18, 18)
                .addComponent(tfVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdresse)
                .addGap(18, 18, 18)
                .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomResp)
                .addGap(18, 18, 18)
                .addComponent(tfNomResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addGap(18, 18, 18)
                .addComponent(btnAnnuler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAnnulerActionPerformed
    {//GEN-HEADEREND:event_btnAnnulerActionPerformed
        FSelectAssociation f1 = new FSelectAssociation();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOkActionPerformed
    {//GEN-HEADEREND:event_btnOkActionPerformed
        try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "" );
        PreparedStatement prepareStmt = conn.prepareStatement("insert into association(refAsso, ville, adresse, nomResponsable) values(?,?,?,?)");
        prepareStmt.setString(1, tfRefAssoc.getText());
        prepareStmt.setString(2, tfVille.getText());
        prepareStmt.setString(3, tfAdresse.getText());
        prepareStmt.setString(4, tfNomResp.getText());
        prepareStmt.executeUpdate();
        conn.close();
        JOptionPane.showMessageDialog(null, "Inssertion de "+ tfRefAssoc.getText()+ " dans les Association réussie !", "Inssertion Réussie", JOptionPane.OK_OPTION);
        } 
        catch ( SQLException e ) 
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur Sql", JOptionPane.OK_OPTION);
        } 
        finally 
        {
            if ( conn != null )
                try {
                    conn.close();
                    } 
                catch ( SQLException ignore ) 
                    {
                    }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FAjoutAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FAjoutAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FAjoutAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FAjoutAssociation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FAjoutAssociation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblNomResp;
    private javax.swing.JLabel lblRefAssoc;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JLabel lblVille;
    private javax.swing.JTextField tfAdresse;
    private javax.swing.JTextField tfNomResp;
    private javax.swing.JTextField tfRefAssoc;
    private javax.swing.JTextField tfVille;
    // End of variables declaration//GEN-END:variables
}
