/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenêtre;
import java.sql.*;
import Metier.*;
import javax.swing.JOptionPane;
/*
 *
 * @author Valoo
 */
public class FSelectPratiquer extends FMaster
{
    String pilote = "org.gjt.mm.mysql.Driver";
    Connection conn;
    Statement stat;
    /*
     * Creates new form FSelectSport
    */
    public FSelectPratiquer()
    {
        initComponents();
        ResultSet rs1;
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gymnase", "root", "");
            stat = conn.createStatement();
            rs1 = stat.executeQuery("Select DISTINCT refAsso from pratiquer");
            while(rs1.next())
            {
                cbxAssoc.addItem(rs1.getString("refAsso"));
            }
            rs1.close();
            conn.close();
        } 
        catch (SQLException | ClassNotFoundException sqlE)
        {
            JOptionPane.showMessageDialog(null, sqlE.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbxAssoc = new javax.swing.JComboBox<>();
        lblTitre = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnSuprimmer = new javax.swing.JButton();
        lblAssoc = new javax.swing.JLabel();
        cbxSport = new javax.swing.JComboBox<>();
        lblSport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un Sport");

        cbxAssoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbxAssoc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxAssocActionPerformed(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitre.setForeground(new java.awt.Color(0, 255, 0));
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Ajouter/Suprimer un lien entre une Association et un Sport");

        btnAjouter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.setPreferredSize(new java.awt.Dimension(72, 25));
        btnAjouter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSuprimmer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSuprimmer.setText("Supprimer");
        btnSuprimmer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSuprimmerActionPerformed(evt);
            }
        });

        lblAssoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAssoc.setForeground(new java.awt.Color(0, 0, 0));
        lblAssoc.setText("Association :");

        cbxSport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        lblSport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSport.setForeground(new java.awt.Color(0, 0, 0));
        lblSport.setText("Sport : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuprimmer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAssoc, javax.swing.GroupLayout.Alignment.CENTER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAssoc, javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbxSport, javax.swing.GroupLayout.Alignment.CENTER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSport, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAssoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSport)
                .addGap(18, 18, 18)
                .addComponent(cbxSport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuprimmer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuprimmerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSuprimmerActionPerformed
    {//GEN-HEADEREND:event_btnSuprimmerActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment suprimmer l'association '"+cbxAssoc.getSelectedItem().toString()+"/"+cbxSport.getSelectedItem().toString() + "' du tableaux Pratiquer ?", "Confirmation Supression ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) 
        {
            try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "" );
            PreparedStatement prepareStmt = conn.prepareStatement("delete from pratiquer where refAsso = ? and nomSport = ? ");
            prepareStmt.setString(1, cbxAssoc.getSelectedItem().toString());
            prepareStmt.setString(2, cbxSport.getSelectedItem().toString());
            prepareStmt.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Supression de l'association :'"+cbxAssoc.getSelectedItem().toString()+"/"+cbxSport.getSelectedItem().toString() +" dans la table accueillir réussie !", "Suppression Réussie", JOptionPane.OK_OPTION);
            } 
            catch ( SQLException e ) 
            {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur Sql", JOptionPane.OK_OPTION);
            } 
            finally 
            {
                if ( conn != null )
                    try {
                        conn.close();
                        } 
                    catch ( SQLException ignore ) 
                        {
                        }
            }
        }
    }//GEN-LAST:event_btnSuprimmerActionPerformed

    private void cbxAssocActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxAssocActionPerformed
    {//GEN-HEADEREND:event_cbxAssocActionPerformed
        ResultSet rs1;
        cbxSport.removeAllItems();
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "");
            stat = conn.createStatement();
            rs1 = stat.executeQuery("Select nomSport from pratiquer where refAsso ='"+cbxAssoc.getSelectedItem()+"'");
            while(rs1.next())
            {
               cbxSport.addItem(rs1.getString("nomSport"));
            }
            rs1.close();
            conn.close();
        } 
        catch (SQLException | ClassNotFoundException sqlE)
        {
            JOptionPane.showMessageDialog(null, sqlE.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbxAssocActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAjouterActionPerformed
    {//GEN-HEADEREND:event_btnAjouterActionPerformed
        FAjoutPratiquer f1 = new FAjoutPratiquer();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnAjouterActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FSelectPratiquer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FSelectPratiquer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FSelectPratiquer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FSelectPratiquer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FSelectPratiquer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnSuprimmer;
    private javax.swing.JComboBox<String> cbxAssoc;
    private javax.swing.JComboBox<String> cbxSport;
    private javax.swing.JLabel lblAssoc;
    private javax.swing.JLabel lblSport;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
