/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenêtre;
import java.sql.*;
import Metier.*;
import javax.swing.JOptionPane;
/*
 *
 * @author Valoo
 */
public class FSelectAcceuillir extends FMaster
{
    String pilote = "org.gjt.mm.mysql.Driver";
    Connection conn;
    Statement stat;
    /*
     * Creates new form FSelectSport
    */
    public FSelectAcceuillir()
    {
        initComponents();
        ResultSet rs1;
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "");
            stat = conn.createStatement();
            rs1 = stat.executeQuery("Select DISTINCT refSalle from accueillir");
            while(rs1.next())
            {
               cbxSalle.addItem(rs1.getString("refSalle"));
            }
        } 
        catch (SQLException | ClassNotFoundException sqlE)
        {
            JOptionPane.showMessageDialog(null, sqlE.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        cbxSalle = new javax.swing.JComboBox<>();
        lblAjoutSport = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        lblSalle = new javax.swing.JLabel();
        lblSport = new javax.swing.JLabel();
        cbxSport = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter un Sport");

        cbxSalle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbxSalle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxSalleActionPerformed(evt);
            }
        });

        lblAjoutSport.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblAjoutSport.setForeground(new java.awt.Color(51, 255, 51));
        lblAjoutSport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjoutSport.setText("Ajouter/Supprimer un lien entre une salle et un Sport");

        btnAjouter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.setPreferredSize(new java.awt.Dimension(72, 25));
        btnAjouter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSupprimerActionPerformed(evt);
            }
        });

        lblSalle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSalle.setText("Salle :");

        lblSport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSport.setText("Sport :");

        cbxSport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblSalle)
                            .addComponent(lblSport)
                            .addComponent(cbxSport, 0, 570, Short.MAX_VALUE)
                            .addComponent(cbxSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblAjoutSport)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAjoutSport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalle)
                .addGap(18, 18, 18)
                .addComponent(cbxSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSport)
                .addGap(18, 18, 18)
                .addComponent(cbxSport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSupprimerActionPerformed
    {//GEN-HEADEREND:event_btnSupprimerActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment suprimmer l'association '"+cbxSalle.getSelectedItem().toString()+"/"+cbxSport.getSelectedItem().toString() + "' du tableaux Accueillir ?", "Confirmation Supression ?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) 
        {
            try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "" );
            PreparedStatement prepareStmt = conn.prepareStatement("delete from accueillir where refSalle = ? and nomSportAutorise = ? ");
            prepareStmt.setString(1, cbxSalle.getSelectedItem().toString());
            prepareStmt.setString(2, cbxSport.getSelectedItem().toString());
            prepareStmt.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Supression de l'association :'"+cbxSalle.getSelectedItem().toString()+"/"+cbxSport.getSelectedItem().toString() +" dans la table accueillir réussie !", "Suppression Réussie", JOptionPane.OK_OPTION);
            } 
            catch ( SQLException e ) 
            {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur Sql", JOptionPane.OK_OPTION);
            } 
            finally 
            {
                if ( conn != null )
                    try {
                        conn.close();
                        } 
                    catch ( SQLException ignore ) 
                        {
                        }
            }
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void cbxSalleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxSalleActionPerformed
    {//GEN-HEADEREND:event_cbxSalleActionPerformed
        ResultSet rs1;
        cbxSport.removeAllItems();
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymnase", "root", "");
            stat = conn.createStatement();
            rs1 = stat.executeQuery("Select nomSportAutorise from accueillir where refSalle ='"+cbxSalle.getSelectedItem().toString()+"'");
            while(rs1.next())
            {
               cbxSport.addItem(rs1.getString("nomSportAutorise"));
            }
            rs1.close();
            conn.close();
        } 
        catch (SQLException | ClassNotFoundException sqlE)
        {
            JOptionPane.showMessageDialog(null, sqlE.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbxSalleActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAjouterActionPerformed
    {//GEN-HEADEREND:event_btnAjouterActionPerformed
        FAjoutAcceuillir f1 = new FAjoutAcceuillir();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnAjouterActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FSelectAcceuillir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FSelectAcceuillir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FSelectAcceuillir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FSelectAcceuillir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FSelectAcceuillir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox<String> cbxSalle;
    private javax.swing.JComboBox<String> cbxSport;
    private javax.swing.JLabel lblAjoutSport;
    private javax.swing.JLabel lblSalle;
    private javax.swing.JLabel lblSport;
    // End of variables declaration//GEN-END:variables
}
