/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenêtre;
import Metier.Reservation;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Valoo
 */
public class FSelectReservationA extends FMaster
{
    ResultSet rs1;
    Statement stat, stat1;
    String RefAssoc, RefSalle, Reserv, Date , Heure;
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");

    public FSelectReservationA()
    {
        initComponents();
        for (int i = 0; i < Reservation.getNbrereservation(); i++) 
        {
            Reservation Re = Reservation.getUneReservation(i);
            cbxReserv.addItem(Re.affich());
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        btnAnnuler = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        lblReservation = new javax.swing.JLabel();
        lblAssoc = new javax.swing.JLabel();
        lblSalle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblHeure = new javax.swing.JLabel();
        cbxReserv = new javax.swing.JComboBox<>();
        cbxAssoc = new javax.swing.JComboBox<>();
        cbxSalle = new javax.swing.JComboBox<>();
        cbxDate = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitre.setForeground(new java.awt.Color(0, 255, 0));
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Selectionnez Une Reservation dans la Base");

        btnAnnuler.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAnnuler.setText("Modifier");

        btnSupprimer.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSupprimer.setText("Supprimer");

        lblReservation.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lblReservation.setText("Réservation : ");

        lblAssoc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAssoc.setText("Associations : ");

        lblSalle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSalle.setText("Salle :");

        lblDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDate.setText("Date : ");

        lblHeure.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHeure.setText("Heure : ");

        cbxReserv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxReserv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxReservItemStateChanged(evt);
            }
        });

        cbxAssoc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxAssoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAssocActionPerformed(evt);
            }
        });

        cbxSalle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        cbxDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jSpinner1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReservation)
                        .addGap(18, 18, 18)
                        .addComponent(cbxReserv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAssoc)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAssoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalle)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeure)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addGap(18, 18, 18)
                        .addComponent(cbxDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxReserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssoc)
                    .addComponent(cbxAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalle)
                    .addComponent(cbxSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeure)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuler)
                    .addComponent(btnSupprimer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxReservItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxReservItemStateChanged

        Reserv = cbxReserv.getSelectedItem().toString();
        String[] ReservSplit = Reserv.split("/");
        RefAssoc = ReservSplit[0];
        cbxAssoc.removeAllItems();
        try
        {
            Class.forName(pilote);
            conn = DriverManager.getConnection("jdbc:mysql://localhost/gymnase", "root", "");
            stat = conn.createStatement();
            rs1 = stat.executeQuery("Select Distinct refAsso from association");
            while(rs1.next())
            {
                cbxAssoc.addItem(rs1.getString("refAsso"));
            }
            for (int i = 0; i < cbxAssoc.getItemCount(); i++) 
            {
                if (RefAssoc.equals(cbxAssoc.getItemAt(i).toString())) 
                {
                    cbxAssoc.setSelectedIndex(i);
                }
            }
            rs1.close();
            stat.close();
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_cbxReservItemStateChanged

    private void cbxAssocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAssocActionPerformed
        Reserv = cbxReserv.getSelectedItem().toString();
        String[] ReservSplit = Reserv.split("/");
        RefSalle = ReservSplit[1];
        cbxSalle.removeAllItems();
        try
            {
                Class.forName(pilote);
                conn = DriverManager.getConnection("jdbc:mysql://localhost/gymnase", "root", "");
                stat = conn.createStatement();
                rs1 = stat.executeQuery("Select Distinct refSalle from salle");
                while(rs1.next())
                {
                    cbxSalle.addItem(rs1.getString("refSalle"));
                }

                for (int i = 0; i < cbxSalle.getItemCount(); i++) 
                {
                    if (RefSalle.equals(cbxSalle.getItemAt(i))) 
                    {
                        cbxSalle.setSelectedIndex(i);
                    }
                }
                rs1.close();
                stat.close();
            }
        catch(ClassNotFoundException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erreur Sql", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_cbxAssocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FSelectReservationA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FSelectReservationA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FSelectReservationA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FSelectReservationA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FSelectReservationA().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox<String> cbxAssoc;
    private javax.swing.JComboBox<String> cbxDate;
    private javax.swing.JComboBox<String> cbxReserv;
    private javax.swing.JComboBox<String> cbxSalle;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAssoc;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHeure;
    private javax.swing.JLabel lblReservation;
    private javax.swing.JLabel lblSalle;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
