/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fenêtre;

/**
 *
 * @author Valoo
 */
public class FStatistique extends FMaster
{

    /**
     * Creates new form FStatistique
     */
    public FStatistique()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSport = new javax.swing.JButton();
        lblTitre = new javax.swing.JLabel();
        btnAssoc = new javax.swing.JButton();
        btnSalle = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Statistique");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(358, 180));

        btnSport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSport.setText("Sport");
        btnSport.setPreferredSize(null);
        btnSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportActionPerformed(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitre.setForeground(new java.awt.Color(51, 255, 51));
        lblTitre.setText("Statistique");

        btnAssoc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAssoc.setText("Association");
        btnAssoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssocActionPerformed(evt);
            }
        });

        btnSalle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSalle.setText("Salle");
        btnSalle.setMaximumSize(new java.awt.Dimension(60, 25));
        btnSalle.setMinimumSize(new java.awt.Dimension(60, 25));
        btnSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalleActionPerformed(evt);
            }
        });

        btnReservation.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReservation.setText("Réservation");
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSport, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssoc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSportActionPerformed
    {//GEN-HEADEREND:event_btnSportActionPerformed
        FStatSport f1 = new FStatSport();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnSportActionPerformed

    private void btnAssocActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAssocActionPerformed
    {//GEN-HEADEREND:event_btnAssocActionPerformed
        FStatAssoc f1 = new FStatAssoc();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnAssocActionPerformed

    private void btnSalleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSalleActionPerformed
    {//GEN-HEADEREND:event_btnSalleActionPerformed
        FStatSalle f1 = new FStatSalle();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnSalleActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReservationActionPerformed
    {//GEN-HEADEREND:event_btnReservationActionPerformed
        FStatReserv f1 = new FStatReserv();
        this.setVisible(false);
        f1.setVisible(true);
    }//GEN-LAST:event_btnReservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FStatistique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssoc;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnSalle;
    private javax.swing.JButton btnSport;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
